#!/usr/bin/env bash
# Installing nginx in different server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "26i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
