#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\listen 293-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 293-web-01 35.237.55.203:80 check\n\tserver 293-web-02 104.196.13.174:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
