#!/usr/bin/env bash
# This script print "To infinity and beyond" forever and use a traps to stop commands
pgrep -f 100-process_and_pid_file > /var/run/holbertonscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; echo "I hate the kill command"; exit' SIGTERM
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
