#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and at 9th print "Hi"
i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    let i=i+1
done
