#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user
sudo pkill apache2
chmod 744 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sed -i 's/#user.*/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
